name: Flask CI/CD

permissions:
  pull-requests: write

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              python-version: ["3.9", "3.10", "3.11"]      
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
                cache: 'pip'
            - run: pip install .

    test:
        needs: build
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.9", "3.10", "3.11"]
    
        steps:
          - uses: actions/checkout@v3
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
              cache: "pip"
          - name: Install package in dev mode
            run: pip install .[dev]
          - name: Install Pytest coverage
            run: |
              pip install pytest-cov
          - name: Build coverage file
            shell: bash -l {0}
            run: |
                pytest --cache-clear --cov=simple_flask tests/ > pytest-coverage.txt      
            # comment coverage 
          - name: Comment coverage
            if: matrix.python-version == '3.11'
            uses: coroo/pytest-coverage-commentator@v1.0.2
    lint:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: psf/black@stable

    type-check:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
                cache: "pip"
            - name: Install package in dev mode
              run: pip install .[dev]
            - name: Run mypy
              shell: bash -l {0}
              run: |
                mypy simple_flask
    docker:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            tags: simple_flask:${{ github.sha }}
